// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Is This Red?",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Is This Red?",
            targets: ["AppModule"],
            bundleIdentifier: "com.eunji.Swift-Student-Challenge.Swift-Student-Challenge",
            teamIdentifier: "AT9KX3ZBW6",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
